version:  '3.7'
services:
  db:
    image: postgres:11
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/data/:/var/lib/postgresql/data:z
    environment:
      POSTGRES_PASSWORD: root
  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    ports:
      - 8080:8080
  nginx:
    container_name: nginx
    build: docker/nginx
    ports:
    - 80:80
    volumes:
    - ./:/var/www/foody
    networks:
      default:
        aliases:
        - foody.test
  foody:
    container_name: foody
    build: docker/php-fpm
    working_dir: /var/www/foody
    volumes:
      - ./:/var/www/foody
